services:
  - type: worker
    name: bayport-scheduler
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node scheduler.js
    envVars:
      - key: NODE_ENV
        value: production
